site_name: Robotics Control Theory
site_description: A mathematical guide to robot kinematics and control.

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# This turns on the math engine for your transformation matrices
markdown_extensions:
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Introduction: index.md
  - Foundations of Robotic Control: 01-foundations-of-robotic-control.md
  - Spatial Representation: 02-spatial-representation.md
  - Kinematics and Trajectory Control: 03-kinematics-and-trajectory-control.md